### ISSUE TITLE
Server Builds But No GUI Opens

### ISSUE THREAD

**Issue by BroCoRo** [OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1#1]
When the server WPF GUI interface is run, it does load a window it just closes right away. There are no warnings or compile time errors, the server builds and open - it simply closes before a window can start.
From what I researched so far it seems to be a common issue but the fixes I have found so far do not seem to work.

**Comment by OGarland001** [comment]
f87218e https://github.com/OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1/commit/f87218e41b188a02a67dd17ae0c0623b05653fc6

fixed the issue the project was thinking that the program.cs file within the model was the correct entry point so it was only running the model. To fix this I just encapsulated the file within a class, so it won't enter until we call it.
