### ISSUE TITLE
Integration Errors, we merged and this is the issues we came with

### ISSUE THREAD

**Issue by OGarland001** [OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1#17]
everything broke, the test cases didn't show up.

client had issue with the namespace being the same as the project.

server test cases didn't show up.

working through the conflicts

**Comment by BroCoRo** [comment]
Had to recopy the server tests, server.cs, packet.cs files from the server branch into the master branch as they did not copy properly. In addition, the client namespace was corrected. Now both the server and client run.
