### ISSUE TITLE
attempting to login with a new user throws exceptions 

### ISSUE THREAD

**Issue by BroCoRo** [OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1#30]
When attempting to log in with a user that has never been on the application before throws exceptions that the use specific file does not exist. The error occurs only for users attempting to login when they should be creating an account since they have never been apart of the system before. The issues occur in the highlighted section of the screenshot below:

<img width="835" alt="image" src="https://user-images.githubusercontent.com/85836332/230483189-7427eb86-9d42-457a-838b-db60ffa2c389.png">

**Comment by tylerscheifley** [comment]
Issue resolved. Added a if statement inside saveUserSpecificeventToFile method check if the directory of the user existing before trying to access it. 

Commit: 98592676b836f31acfeb569a5c08ab212d8b3a4a
