### ISSUE TITLE
Server.cs  Displays 8 Errors

### ISSUE THREAD

**Issue by tylerscheifley** [OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1#8]
8 new errors randomly showed up after building the solution.
<img width="684" alt="errors" src="https://user-images.githubusercontent.com/90644730/228010282-24a27d89-0c49-485b-a6f3-a9c6e3df77af.png">

**Comment by BroCoRo** [comment]
From what I saw, these errors are stemming from the compiler now getting confused as to what using each of the listed lines in your 8 errors are relying on. The fix could be to specify which usings each line should be using.

For example, adding:
using Image = System.Drawing.Image;
using Point = System.Drawing.Point;
using FontStyle = System.Drawing.FontStyle;

I made these changes and it appears to build and run now!

Link to fix commit:
[https://github.com/OGarland001/COMP72070-23W-Sec1-Project-IV-Group-1/commit/73a07810fa933fc5f8f6bbe726cc2d74ebb27c31](url)
